version: '1'
services:
  db:
      image: mysql/mysql-server
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
            - "3306:3306"
      environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: chat-app
            MYSQL_ROOT_HOST: "%"

  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
            - '6379:6379'
      command: redis-server
      volumes: 
            - redis:/data

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
      container_name: elasticsearch
      restart: always
      environment:
            - xpack.security.enabled=false
            - discovery.type=single-node

      ulimits:
            memlock:
                  soft: -1
                  hard: -1
            nofile:
                  soft: 65536
                  hard: 65536
      volumes:
            - elasticsearch-config-volume:/usr/share/elasticsearch/config
            - elasticsearch-data-volume:/usr/share/elasticsearch/data
      ports:
            - 9200:9200
            - 9300:9300
      

  web:
      build: .
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes: 
            - ".:/chat-app"
      ports: 
            - "3000:3000"
      depends_on:
            - db
            - redis
            - elasticsearch
      links:
            - db
            - redis
            - elasticsearch
      environment:
            DB_USER: root
            DB_NAME: chat-app
            DB_PASSWORD: 123456
            DB_HOST: db
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_URL : redis://redis:6379/0
            ELASTIC_HOST: elasticsearch
volumes:
  redis:
  elasticsearch-data-volume: 
  elasticsearch-config-volume:
